version: '3.8'

services:
  loadbalancer_server:
    image: srikarthickk/loadbalancer_server:latest
    container_name: loadbalancer_server_container
    working_dir: /app/db-infra-active-loadbalancer-server
    ports:
      - "4000:4000"
    networks:
      - default
    command: ["node", "index.js"]

  loadbalancer_client:
    image: srikarthickk/loadbalancer_client:latest
    working_dir: /app/db-infra-active-loadbalancer-client
    container_name: loadbalancer_client
    ports:
      - "3001:3001"
    networks:
      - default
    depends_on:
      - loadbalancer_server
    command: ["serve", "-s", "build", "-l", "3001"]
